version: 2
jobs:
  dependencies:
    pre:
      - pip install -f requirements.txt
  build:
    machine: true
    steps: 
      - checkout
      - run: python run.py ; python tests/artist_id_test.py 
workflows:
  version: 2
  buil:
    jobs:
      - build

