version: 2
jobs:
  build:
    docker:
      - image: davidfic/bandfinder:latest
    steps:
      - checkout
      - run: apt update && apt install -y curl && curl localhost:5555
workflows:
  version: 2
  buil:
    jobs:
      - build

