version: 2
jobs:
  build:
    docker:
      - image: circleci/python:2.7.13
    steps:
      - checkout
      - run: pip install -r requirements.txt
      - run: python run.py
      - run: python tests/artist_id_test.py